# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2020-05-26 08:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, verbose_name='故事标题')),
                ('song_name', models.CharField(max_length=64, verbose_name='歌曲名称')),
                ('image_url', models.CharField(max_length=126, verbose_name='图片URL')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='故事内容')),
                ('comment_num', models.IntegerField(verbose_name='评论数')),
                ('like_num', models.IntegerField(verbose_name='点赞数')),
                ('view_num', models.IntegerField(verbose_name='浏览数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='StoryViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='浏览用户id'), blank=True, size=None)),
                ('story_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='story.Story', verbose_name='故事id')),
            ],
            options={
                'db_table': 'story_view_record',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名称')),
                ('sex', models.IntegerField(null=True, verbose_name='性别')),
                ('intro', models.CharField(default='', max_length=1024, verbose_name='签名')),
                ('avatar', models.CharField(max_length=126, verbose_name='头像URL')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='story.User', verbose_name='创建人'),
        ),
    ]
